
set(cmake_common_args
    -DCMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -DLIB_SUFFIX:STRING=${LIB_SUFFIX}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}/INSTALL
    -DUSE_CLANG:BOOL=${USE_CLANG}
    -DUSE_SUPERBUILD:BOOL=OFF
    -DMAKE_TESTS:BOOL=${MAKE_TESTS}
    -DUSE_DOXYGEN:BOOL=${USE_DOXYGEN}
    -DMAKE_STATIC_LIB:BOOL=${MAKE_STATIC_LIB}
    -DMAKE_DEB_PACKAGE:BOOL=${MAKE_DEB_PACKAGE}
    -DCMAKE_BUILD_TYPE:STRING=${CMAKE_BUILD_TYPE}
)

##JsonBox
#if(GIT_HTTPS)
#    set(JsonBox_REPO "https://github.com/anhero/JsonBox.git")
#else()
#    set(JsonBox_REPO "git@github.com:anhero/JsonBox.git")
#endif()
#
ExternalProject_Add(
  JsonBox
  SOURCE_DIR "${CMAKE_SOURCE_DIR}/JsonBox"
  CMAKE_ARGS
    -DCMAKE_C_COMPILER:PATH=${CMAKE_C_COMPILER}
    -DCMAKE_CXX_COMPILER:PATH=${CMAKE_CXX_COMPILER}
    -DCMAKE_CXX_FLAGS:STRING=${CMAKE_CXX_FLAGS}
    -DLIB_SUFFIX:STRING=${LIB_SUFFIX}
    -DCMAKE_INSTALL_PREFIX:PATH=${CMAKE_BINARY_DIR}/INSTALL
    -DCMAKE_INSTALL_RPATH:PATH=${CMAKE_BINARY_DIR}/INSTALL/lib${LIB_SUFFIX}
    -DCMAKE_INSTALL_LIBDIR:PATH=lib
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
)

#AquetiTools
ExternalProject_Add(
  AquetiTools
  SOURCE_DIR "${CMAKE_SOURCE_DIR}"
  CMAKE_ARGS 
    ${cmake_common_args} 
  BUILD_ALWAYS 1
  INSTALL_DIR ${CMAKE_INSTALL_PREFIX}
  LOG_INSTALL 1
  DEPENDS JsonBox
)
